Fix "subcommand wasn't recognized" when invoked under `cargo`
Users are seeing:

    error: The subcommand 'dependency-inheritor' wasn't recognized

            Did you mean 'dependency-inherit'?

This happens because the resulting exectuable is
`cargo-dependency-inheritor` (this package name), which cargo invokes
with `dependency-inheritor` as subcommand whereas the `Cargo` enum
variant was expecting `dependency-inherit` (based on
`DependencyInherit`).